### ISSUE TITLE
关于cookie

### ISSUE THREAD

**Issue by Alexwangziyu** [zhstark/crawler_1point3#5]
看了下 这个crawler不涉及登录，而且整页整页取所以频率很低，没有cookie的问题。想请问下作者了不了解如果需要爬帖子内容的话，账号有限的情况下怎么避免被检测到cookie异常？谢谢

**Comment by zhstark** [comment]
> 看了下 这个crawler不涉及登录，而且整页整页取所以频率很低，没有cookie的问题。想请问下作者了不了解如果需要爬帖子内容的话，账号有限的情况下怎么避免被检测到cookie异常？谢谢

请求ip别频繁变换，控制请求频率等。怎么样像人为请求怎么来[doge]
